feature/lesson5 resolving lesson 5 task
Nadya101/HomeworkFromNikita pull request #1
Opened 2021-09-14 20:25 UTC by Nadya101

2021-09-14 20:34 UTC, Nadya101 commented
**_I sincerely wish you happy and bug-free coding!_** [https://xbsoftware.com/wp-content/uploads/2018/09/700.gif](url)

2021-09-15 14:33 UTC, Nadya101 commented
Этот реквест я могу  закрыть?

2021-09-16 08:58 UTC, nickrogracher requested changes
Сделай несколько мелких изменений. 
И скажи честно, ты запускала эту программу?=)

2021-09-16 08:58 UTC, nickrogracher commented on src/Lesson5/Computer.java
> +    boolean zorstkijDisk;
@Nadya101 
Поменяй названия переменных на без транслитные
```suggestion
    boolean cpu; //поля екзепляров
    boolean ram;
    boolean hdd;
```

2021-09-16 08:58 UTC, nickrogracher commented on src/Lesson5/Computer.java
> +    int resursPolnogoCykluRaboty;
@Nadya101 транслитерация запрещена
```suggestion
    int максКоличествоВыключений(на англ);
```

2021-09-16 08:58 UTC, nickrogracher commented on src/Lesson5/Computer.java
> +        this.resursPolnogoCykluRaboty = resursPolnogoCykluRaboty;
@Nadya101 сделай конструктор валидным, исходя из изменения имен переменных выше

2021-09-16 08:58 UTC, nickrogracher commented on src/Lesson5/Computer.java
> +    void opisanie() {
@Nadya101 транслитерация запрещена, имя = англ слово. Поменяй название `opisanie()`

2021-09-16 08:58 UTC, nickrogracher commented on src/Lesson5/Computer.java
> +        System.out.print("Процесор: " + procesor + ", оперативка: " + operativka + ", жесткий диск: " + zorstkijDisk + ", ресурс полных циклов работы: " + resursPolnogoCykluRaboty);
@Nadya101 Не принято, чтобы строка кода выходила за границы монитора. нужно разбивать и переносить такую строку
```suggestion
        System.out.print("Процесор: " + procesor + ", оперативка: " + operativka + ", 
        жесткий диск: " + zorstkijDisk + ", ресурс полных циклов работы: " +
        resursPolnogoCykluRaboty);
```

2021-09-16 08:58 UTC, nickrogracher commented on src/Lesson5/Computer.java
> +        System.out.print("]\n");
@Nadya101 Зачем `print("]\n")`? Можно ведь сделать в 46 строке `println`, будет тоже самое

2021-09-16 08:58 UTC, nickrogracher commented on src/Lesson5/Computer.java
> +    boolean proverkaNaZboj() {
@Nadya101 транслитерация запрещена. Дай название методу `proverkaNaZboj()` на англ языке

2021-09-16 08:58 UTC, nickrogracher commented on src/Lesson5/Computer.java
> +        System.out.print("Введите число 0 или 1 -> ");
@Nadya101 а почему вывод без переноса курсора на новую строку?

2021-09-16 08:58 UTC, nickrogracher commented on src/Lesson5/Computer.java
> +        }
@Nadya101 Совет, если тебе много условий проверить надо, чтобы все они выполнялись, то лучше проверять обратное им условие, чтобы хоть один не совпадал
```suggestion
       if (!procesor || !operativka || !zorstkijDisk || resursPolnogoCykluRaboty > 0 || (!isOn) & (!isDead)) {//проверяем если хоть что-то не исправно
            .......
            Далее вся логика переделывается уже исходя из того, что мы сначала проверили на поломки, а не 
            на исправность всего сразу
```
Ты также использовала `&`, а нодо было `&&` (1 - складывает 2 значения, а второй добавляет еще 1 условие с помет `И`.

2021-09-16 08:58 UTC, nickrogracher commented on src/Lesson5/Computer.java
> +      boolean vykluchytComputer() {
@Nadya101 Транслитерация запрещена. Измени имя метода на англ слово

2021-09-16 08:58 UTC, nickrogracher commented on src/Lesson5/Computer.java
> +        if (isOn & (!isDead)) {  //только если компьютер включен и не умер
@Nadya101 неверный символ одновременной отработки 2-ух условий. Верный - `&&`

2021-09-16 09:21 UTC, nickrogracher commented
> Этот реквест я могу  закрыть? 

А ты изменения сделала? Закоммитила?

2021-09-16 09:32 UTC, Nadya101 commented on src/Lesson5/Computer.java
> +    boolean zorstkijDisk;
![Screen HW lesson5](https://user-images.githubusercontent.com/44065623/133587835-c5e9befe-191b-43e2-abf8-88da754bd798.PNG)

Да, я запускала программу перед тем как отправить.

2021-09-16 09:43 UTC, Nadya101 commented on src/Lesson5/Computer.java
> +        this.resursPolnogoCykluRaboty = resursPolnogoCykluRaboty;
Я делаю refactor-> rename и все названия меняются автоматически)

2021-09-16 09:44 UTC, Nadya101 commented on src/Lesson5/Computer.java
> +    int resursPolnogoCykluRaboty;
поменяла на int MaxNumberOfShutdowns;

2021-09-16 09:44 UTC, Nadya101 commented on src/Lesson5/Computer.java
> +    void opisanie() {
Поменяла на getDescription();

2021-09-16 09:46 UTC, Nadya101 commented on src/Lesson5/Computer.java
> +        System.out.print("Процесор: " + procesor + ", оперативка: " + operativka + ", жесткий диск: " + zorstkijDisk + ", ресурс полных циклов работы: " + resursPolnogoCykluRaboty);
Строку разбила и перенесла

2021-09-16 09:48 UTC, Nadya101 commented on src/Lesson5/Computer.java
> +        System.out.print("]\n");
исправлено на System.out.println("]");

2021-09-16 09:51 UTC, Nadya101 commented on src/Lesson5/Computer.java
> +    boolean proverkaNaZboj() {
поменяла на CheckingForFailure();

2021-09-16 09:53 UTC, Nadya101 commented on src/Lesson5/Computer.java
> +        System.out.print("Введите число 0 или 1 -> ");
Поменяла на         System.out.println("Введите число 0 или 1 -> ");
_мне просто так нравилось больше, пишешь где стрелка показывает)_

2021-09-16 10:33 UTC, Nadya101 commented on src/Lesson5/Computer.java
> +      boolean vykluchytComputer() {
назва метода  boolean offComputer();

2021-09-16 11:02 UTC, Nadya101 commented on src/Lesson5/Computer.java
> +        }
@nickrogracher вот здесь не поняла. Переделала так: 
  _boolean onComputer() {
        CheckingForFailure();
        if (!cpu || !ram || !hdd || maxNumberOfShutdowns == 0 || (isDead)) {//проверяем если хоть что-то не исправно
            System.out.println("Невозможно включить компьютер :(");
            isOn = false;
            getDescription();
        } else if (isOn) {
            System.out.println("Компьютер уже был включен!");
        } else {
            isOn = true;
            System.out.println("Компьютер включен!");
        }
        return isOn;_

2021-09-16 11:03 UTC, Nadya101 commented on src/Lesson5/Computer.java
> +        if (isOn & (!isDead)) {  //только если компьютер включен и не умер
Исправлено:   if (isOn && (!isDead)) {}

2021-09-16 11:37 UTC, Nadya101 commented
@nickrogracher все изминение сделаны и закоммичены. Програма работает:
![HW lesson5](https://user-images.githubusercontent.com/44065623/133604901-0176ef37-7e1c-4dc3-9d8f-09f6c3158613.PNG)

но я спрашывала так как здесь я забросила согласно заданию на последнем уроке, а дней 7 назад закоммитела этот код на проект Teaching.

Должна ли я сделать новую ветку и забросить сюда и задание с урока 6 ?

2021-09-16 16:10 UTC, nickrogracher approved these changes
Good

2021-09-16 16:13 UTC, merged